---
version: "2.1"
services:
  projectsend_database:
    image: mariadb
    container_name: projectsend_database
    hostname: projectsend_database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: projectsend
    volumes:
      - ${PWD}/database:/var/lib/mysql
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MAX_UPLOAD=5000
    volumes:
      - ${PWD}/projectsend/config
      - ${PWD}/projectsend/data
    ports:
      - 172.17.0.1:58080:80
    restart: unless-stopped
  autossh:
    image: jnovack/autossh
    container_name: autossh-projectsend
    environment:
      - SSH_REMOTE_USER=projectsend
      - SSH_REMOTE_HOST=gateway.mikush.in
      - SSH_REMOTE_PORT=2221
      - SSH_TARGET_HOST=172.17.0.1
      - SSH_TARGET_PORT=58080
      - SSH_TUNNEL_PORT=58080
    restart: always
    volumes:
      - ${PWD}/id_rsa:/id_rsa
